### ISSUE TITLE
Can't download nuget packages

### ISSUE THREAD

**Issue by jakobstanford** [Giorgi/DuckDB.NET#116]
Hi, 

not sure if a bug, but I've been trying download the latest alpha version nuget packages from github.
For example, from this link: https://github.com/Giorgi/DuckDB.NET/pkgs/nuget/DuckDB.NET.Data.Full

But on that page, I dont see any download link. After some research I figured that I can add github has package source in the Nuget package manager. (using the URL https://nuget.pkg.github.com/Giorgi/index.json ) but this URL asks me for authentication. Not sure if I need to be logged in to download a publicly available nuget package.

What am I missing?

**Comment by jakobstanford** [comment]
Thanks, I will give that a try.

**Comment by Seddryck** [comment]
According to my experience, GitHub package is an issue. I'm using appVeyor and if I want to use the GitHub token as a secret (encrypted), it's not working for pull requests (because it would be a potential security, someone pushing to your branch and displaying the non encrypted token). IMO would be more convenient to also push alpha to Nuget but your mileage may vary.

**Comment by jakobstanford** [comment]
Actually, it seems like the token expires after 30 days too.
Is there a project specific setting to make nuget packages 'public'?

**Comment by Giorgi** [comment]
You can set the token lifetime when creating it.
