### ISSUE TITLE
Install MySQL extension download link error

### ISSUE THREAD

**Issue by netnr** [Giorgi/DuckDB.NET#176]
HTTP Error: Failed to download extension "mysql_scanner" at URL "http://extensions.duckdb.org/4a89d97db8/windows_amd64/mysql_scanner.duckdb_extension.gz"
Extension "mysql_scanner" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.

```sql
select version();
-- v0.10.1-dev1494
```

```
C:\Users\Administrator\.duckdb\extensions\`4a89d97db8`\windows_amd64\mysql_scanner.duckdb_extension
↓
C:\Users\Administrator\.duckdb\extensions\`v0.10.0`\windows_amd64\mysql_scanner.duckdb_extension
```

Manually copy a copy to 4a89d97db8. The query shows that it is installed, but an error occurs during LOAD.

Invalid Input Error: Extension "`C:\Users\Administrator\.duckdb\extensions\4a89d97db8\windows_amd64\mysql_scanner.duckdb_extension`" version (v0.10.0) does not match DuckDB version (v0.10.1-dev1494)

**Comment by Giorgi** [comment]
This is a known issue in DuckDB: https://discord.com/channels/909674491309850675/921073327009853451/1219587757891129458

**Comment by Giorgi** [comment]
MySql scanner hasn't been updated to 0.10.1 yet either: https://github.com/duckdb/duckdb_mysql/pull/46

**Comment by gitfvb** [comment]
Thanks @Giorgi , so the extensions like postgres and sqlite need to be updated to `v0.10.1` then it should work straight away?

**Comment by Giorgi** [comment]
@gitfvb I'm not sure if other extensions have been updated already or not, you should probably ask the DuckDB team but the situation with loading extensions is more tricky. In yesterday's release, the libduckdb version was `v0.10.1-dev1494`. Because of the suffix, it's unable to load any extension. The DuckDB team re-uploaded libduckdb with the correct version but because NuGet shipped with yesterday's libduckdb you won't be able to load any extensions until I publish a new version.

But this issue is only for the Windows version of `libduckdb`, it should work fine on other platforms.

**Comment by gitfvb** [comment]
Ok, thanks for the quick reply @Giorgi
Then I will need to wait 😊

**Comment by Giorgi** [comment]
@gitfvb In the meantime you can use DuckDB.NET.Data package together with the libduckdb library from 0.10.1 release.

**Comment by gitfvb** [comment]
Hi @Giorgi , oh nice! That worked straight away just replacing the dll file. So cool... using duck db to use multiple databases through ADO.NET

Thanks :-)

**Comment by Giorgi** [comment]
Closing the issue as MySql extension is updated to 0.10.1 and usable from .Net with the above workaround.

**Comment by Giorgi** [comment]
@gitfvb I just uploaded a new version on NuGet that includes the fixed version of the DuckDB library.

**Comment by gitfvb** [comment]
Perfect, thanks @Giorgi 👍
